```{r}
library(mongolite)
library(glue)

username = 'benjaminhoskings'
password = 'i6UMmr7TpOcIOUcc'

# 'mongodb+srv://{username}:{password}@cluster0.w6iufqn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'

connection_string = sprintf('mongodb+srv://%s:%s@cluster0.w6iufqn.mongodb.net/?retryWrites=True&w=majority&appName=Cluster0', username, password)

consults_db = mongo(collection="activity_data", db="godiva_data", url=connection_string)
athlete_db = mongo(collection="athlete_data", db="godiva_data", url=connection_string)
```

Search the MongoDB database for the desired fields.

```{r}
extract_activity_fields = c(
  "id", "name", "distance", "moving_time", "elapsed_time", "athlete_id"
)


query_string = paste0('{"', paste(extract_activity_fields, collapse ='": true, "'), '": true}');
q_string = '{"name": true, "distance": true}'
q = consults_db$find(fields=query_string)
```

Select the users!

```{r}
user_select <- unique(consults_db$find(fields = '{"athlete_id": true}')$athlete_id)
names(user_select) <- paste("User ", user_select)

query = athlete_db$find(sprintf('{"group": "%s"}', "REPS"))
```

```{r}
query = consults_db$find(sprintf('{"athlete_id": %s, "sport_type": {"$regex": "Sw"}}', user_select[1]))

query = consults_db$find(sprintf('{"athlete_id": %s, "start_date_local": {"$regex": "2024-06"}}', user_select[1]))
# query = consults_db$find('{"sport_type": "Swim"}')

# sprintf('{"athlete_id": %s, "sport_type": "Swim}', user_select[1]))
# "start_date": {"$regex" : "/2024/"}

query = consults_db$find(sprintf('{"date": {"$regex" : "2024"}}', user_select[1]))

athlete_data = athlete_db$find()
athlete_data <- athlete_data |> 
  dplyr::mutate(full_name = paste(first_name, last_name, sep = " "))

athlete_id_map <- athlete_data$strava_id
names(athlete_id_map) <- athlete_data$full_name
athlete_id_map
```

```{r}
map_db_to_list <- function(db_result) {
  all_consults <- list()
  for (idx in 1:nrow(db_result)) {
    df_row <- db_result |>
      dplyr::slice(idx)

    all_consults[[paste(df_row$activity_id)]] <- list(
      "activity_id"=paste(df_row$activity_id),
      "user_id"=df_row$athlete_id, "start_date"=df_row$start_date,
      "sport_type"=df_row$sport_type, "name"=df_row$name,
      "description"=df_row$description,
      "overview" =list(
        "distance"=as.numeric(df_row$distance), "elapsed_time"=as.numeric(df_row$elapsed_time),
        "moving_time" = as.numeric(df_row$moving_time)
      ), 
      "data_streams"=df_row$data_streams
    )
  }

  return(all_consults)
}

query_list <- map_db_to_list(query)
```

```{r}
library(lubridate)
generate_activity_overview <- function(activity_list, date_range) {
  activity_df <- data.frame(matrix(ncol=8, nrow=0))
  colnames(activity_df) <- c(
    "activity_id", "name", "description", "start_date", "sport_type", "distance", "elapsed_time", "moving_time"
  )
  for (activity in activity_list) {
    activity_df[nrow(activity_df) + 1,] = c(
      activity$activity_id, activity$name,
      activity$description, paste(activity$start_date),
      activity$sport_type, activity$overview$distance,
      activity$overview$elapsed_time, activity$overview$moving_time
    )
  }

  activity_df <- activity_df |>
    dplyr::mutate(
      start_date = as_datetime(start_date),
      distance = as.numeric(distance),
      distance_m = distance,
      distance_yd = distance_m * 1.0936132983,
      distance_km = distance / 1000,
      distance_miles = distance_km * 0.6213711922,
      elapsed_time = as.numeric(elapsed_time),
      moving_time = as.numeric(moving_time)
    )


  return(activity_df)
}

activity_df = generate_activity_overview(query_list)
```

```{r}
library(ggplot2)

#' Return distance unit for a given sport
#'
#' @param sport_type Strava sport type (Run, Ride, Swim, etc...)
#' @param system Measurement system (imperial or metric)
#'
#' @return Unit as a string
#' @export
#'
#' @examples get_distance_unit("Run", "metric")
get_distance_unit <- function(sport_type, system) {
  unit <- dplyr::case_when(
    sport_type %in% c("Run", "Ride") ~ {
      if (system == "metric") {"km"} else {"mi"}
    },
    sport_type %in% c("Swim") ~ {
      if (system == "metric") {"m"} else {"yd"}
    },
    .default = NULL
  )
}

get_pace_unit <- function(sport_type, system) {
  unit <- dplyr::case_when(
    sport_type %in% c("Run", "Ride") ~ {
      if (system == "metric") {"min_km"} else {"min_mi"}
    },
    sport_type %in% c("Swim") ~ {
      if (system == "metric") {"min_m"} else {"min_yd"}
    },
    .default = NULL
  )
}

get_speed_unit <- function(sport_type, system) {
  unit <- dplyr::case_when(
    sport_type %in% c("Run", "Ride") ~ {
      if (system == "metric") {"km_hour"} else {"mi_hour"}
    },
    sport_type %in% c("Swim") ~ {
      if (system == "metric") {"m_min"} else {"yd_min"}
    },
    .default = NULL
  )
}

get_activity_metric <- function(data_streams, unit_string) {
  values <- switch(unit_string, 
    # distance values
    "mi" = {data_streams$distance_mi}, "km" = {data_streams$distance_km},
    "yd" = {data_streams$distance_yd}, "m" = {data_streams$distance_m},
    
    # Pace values
    "min_mi" ={diff(c(0, data_streams$time / 60)) / diff(c(0, data_streams$distance_mi))},
    "min_km" ={diff(c(0, data_streams$time / 60)) / diff(c(0, data_streams$distance_km))},
    "min_yd" ={diff(c(0, data_streams$time / 60)) / diff(c(0, 100*data_streams$distance_yd))},
    "min_m" = {diff(c(0, data_streams$time / 60)) / diff(c(0, 100*data_streams$distance_m))},
    
    # Speed values
    "mi_hour" ={diff(c(0, data_streams$distance_mi)) / diff(c(0, data_streams$time / 3600))},
    "km_hour" ={diff(c(0, data_streams$distance_km)) / diff(c(0, data_streams$time / 3600))},
    "yd_min" ={diff(c(0, 100*data_streams$distance_yd)) / diff(c(0, data_streams$time / 60))},
    "m_min" = {diff(c(0, 100*data_streams$distance_m)) / diff(c(0, data_streams$time / 60))},
    data_streams$time)
}
  
generate_activity_graph <- function(activity, x_var, y_var, settings, line_colour=NULL, plot_colour=NULL, bg_colour=NULL) {

  stream_data = activity$data_streams
  stream_df <- data.frame(matrix(unlist(stream_data), ncol=length(stream_data)),stringsAsFactors=FALSE)
  names(stream_df) <- names(stream_data)
  stream_df <- stream_df |>
    dplyr::mutate(
      distance = as.numeric(distance),
      distance_m = distance,
      distance_yd = distance_m * 1.0936132983,
      distance_km = distance / 1000,
      distance_mi = distance_km * 0.6213711922
    )
  
  distance_labels = list(
    "km"="Distance / km", "mi"="Distance / mi",
    "m"="Distance / m", "yd"="Distance / yd",
    "distance"="Distance")
  
  pace_labels = list(
    "min_mi"="Pace / min per mile", "min_km"="Pace / min per km", 
    "min_yd"="Pace / min per 100yd", "min_m"="Pace / min per 100m"
  )
  
  speed_labels = list(
    "mi_hour"="Speed / mph", "km_min"="Speed / kmph", 
    "yd_min"="Pace / 100yd per min", "m_min"="Speed / 100m per min"
  )
  
  x_settings <- switch(x_var, 
    "time" = {
      graph_settings <- list(
        "x_data"=stream_data$time[[1]], "x_label"= "Time"
      )
    }, 
    "distance" = {
      distance_unit <- get_distance_unit(activity$sport_type, settings[activity$sport_type])
      distance_vals <- get_activity_metric(stream_df, distance_unit)
    
      graph_settings <- list(
        "x_data"=distance_vals, "x_label"= paste("Distance /", distance_unit)
      )
    } 
  )
  
  y_settings <- switch(y_var, 
    "heartrate" = {
      graph_settings <- list("data"=stream_data$heartrate[[1]], "label"= "Heart Rate / bpm")
    }, 
    "altitude" = {
      graph_settings <- list("data"=stream_data$altitude[[1]], "label"= "Elevation / m")
    }, 
    "temp" = {
      graph_settings <- list("data"=stream_data$temp[[1]], "label"= "Temperature / degrees")
    }, 
    "distance" = {
      distance_unit <- get_distance_unit(activity$sport_type, settings[activity$sport_type])
      distance_vals <- get_activity_metric(stream_df, distance_unit)
      graph_settings <- list("data"=distance_vals, "label"= paste("Distance /", distance_unit))
    }, 
    "pace" = {
      pace_unit <- get_pace_unit(activity$sport_type, settings[activity$sport_type])
      print(pace_unit)
      pace_vals <- get_activity_metric(stream_df, pace_unit)
      pace_vals[pace_vals > 30] = NA
      graph_settings <- list("data"=pace_vals, "label"= pace_labels[pace_unit])
    }, 
    "speed" = {
      pace_unit <- get_speed_unit(activity$sport_type, settings[activity$sport_type])
      print(pace_unit)
      pace_vals <- get_activity_metric(stream_df, pace_unit)
      pace_vals[pace_vals > 30] = NA
      graph_settings <- list("data"=pace_vals, "label"= speed_labels[pace_unit])
    }
  )
  
  plot_data = data.frame(x = x_settings$x_data, 
                         y = rtrend::movmean(y_settings$data, 10))
  
  p <- ggplot(plot_data, aes(x=x, y=y, group=1)) + 
    xlab(x_settings$x_label) + ylab(y_settings$label) +
    geom_line(aes(color=line_colour)) +
    scale_color_manual(values=c(line_colour, "red", "green")) +
    theme(
      panel.background = element_rect(fill = 'white', color = 'white'),
      panel.grid.major.x = element_line(color = 'lightgrey'),
      panel.grid.major.y = element_line(color = 'lightgrey'),
      legend.position="none")
  
  if (x_var == "time") {
    p <- p + scale_x_time(labels = function(l) {
      dplyr::case_when(
        l < 3600 ~ {strftime(l, '%M:%S')}, 
        .default = {strftime(l, '%H:%M:%S')}
      )
    })
  }

  if (!is.null(bg_colour)) {
    p + theme(plot.background = element_rect(fill=bg_colour, color=bg_colour))
  } else {p}
}

stream_data = query_list[[2]]
unit_settings = c("Run"="imperial", "Swim"="metric", "Ride"="imperial")

generate_activity_graph(stream_data, "distance", "speed", unit_settings)
```

```{r}

library(rtrend)

rtrend::movmean(1:100, 5)
```

```{r}
library(zoo)

activity = query_list[[2]]
unit_settings = c("Run"="imperial", "Swim"="metric", "Ride"="imperial")


stream_data = activity$data_streams
stream_df <- data.frame(matrix(unlist(stream_data), ncol=length(stream_data)),stringsAsFactors=FALSE)

names(stream_df) <- names(stream_data)

distance_labels = list(
  "distance_km"="Distance / km", "distance_mi"="Distance / mi",
  "distance_m"="Distance / m", "distance_yd"="Distance / yd",
  "distance"="Distance")

distance_unit <- get_distance_unit(activity$sport_type, unit_settings[activity$sport_type])
if (!is.null(distance_unit)) {
  distance_col <- paste0("distance_", distance_unit)
} else {
  distance_col <- "distance"
}

stream_df <- stream_df |>
dplyr::mutate(
  distance = as.numeric(distance),
  distance_m = distance,
  distance_yd = distance_m * 1.0936132983,
  distance_km = distance / 1000,
  distance_mi = distance_km * 0.6213711922,
  distance_col = dplyr::pull(stream_df, distance_col), 
  pace = diff(c(0, distance_col)) / diff(c(0, time))
)

plot_vals <- stream_df |>
    dplyr::pull("heartrate") |>
    rtrend::movmean(4)

distance_col = "distance_m"
stream_df_2 <- stream_df |> 
  dplyr::mutate(
    plot_vals = plot_vals)

stream_df_2[as.matrix(stream_df_2) == Inf]  <- 0
```

```{r}

names = list()

options = c("heartrate")

for (i in 1:length(options)) {
  names[[i]] = c("time", options[i])
}

names
```

```{r}
units = list("Run"="imperial", "Swim"="metric", "Ride"="imperial")
units$Run
```
